In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(5)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
tensor_zero_d.ndim

0

In [4]:
tensor_one_d = tf.constant([1, 2])
tensor_one_d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [5]:
tensor_one_d.ndim

1

In [10]:
tensor_two_d = tf.constant([[1,2], [3,4]], dtype = tf.float16)

In [11]:
tensor_two_d

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [12]:
tensor_two_d.ndim

2

In [13]:
casted_tensor = tf.cast(tensor_two_d, dtype = tf.int64)

In [14]:
casted_tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]], dtype=int64)>

In [15]:
tf.size(casted_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>