In [1]:
# fundamental concepts of tensors using tensorflow

import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# creating tensors

scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions
scaler.ndim

0

In [4]:
# creating a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[1,2],
                    [40, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [40,  5]])>

In [7]:
matrix.ndim

2

In [9]:
# Creating tensor

tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[6, 7, 1],
                     [9, 10, 2]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  1],
        [ 9, 10,  2]]])>

In [10]:
tensor.ndim

3

In [16]:
# working with variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor,


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,)

In [17]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [19]:
# let's try to change a element of changeable_tensor
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [20]:
changeable_tensor[1] = 10

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
changeable_tensor[1].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 10])>

In [22]:
unchangeable_tensor[1].assign(10)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [23]:
# Creating random tensor

random_a = tf.random.set_seed(7)
random_a = tf.random.normal(shape=[2,2])
random_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5983449 , 0.06276207],
       [0.14631742, 0.48481876]], dtype=float32)>

In [24]:
# Creating random tensor

random_b = tf.random.set_seed(7)
random_b = tf.random.normal(shape=[2,2])
random_b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5983449 , 0.06276207],
       [0.14631742, 0.48481876]], dtype=float32)>

In [26]:
# Creating random tensor

random_c = tf.random.set_seed(1)
random_c = tf.random.normal(shape=[2,2])
random_c
# random equality depends on set_seed

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1012203 ,  1.5457517 ],
       [ 0.383644  , -0.87965786]], dtype=float32)>

In [28]:
# shuffle a tensor

not_shuffled = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [29]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])>

In [30]:
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])>

In [31]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [35]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled
#every time it changes it's pattern

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])>

In [50]:
# to fixed pattern
tf.random.set_seed(7) # global level seed
shuffled = tf.random.shuffle(not_shuffled, seed = 7) # operation level seed
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])>

In [51]:
# Create a tensor of all 1
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [52]:
tf.zeros(shape=[5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [53]:
import numpy as np
numpy_array = np.arange(5, 29)

In [54]:
numpy_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28])

In [56]:
numpy_array.shape

(24,)

In [57]:
# numpy array to tensor
tensor = tf.constant(numpy_array)

In [58]:
tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28])>

In [59]:
tensor = tf.constant(numpy_array, shape = (3, 8))

In [60]:
tensor

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28]])>

In [61]:
tensor.ndim

2

In [62]:
tensor2 = tf.constant(numpy_array, shape=(2, 3, 4))

In [63]:
tensor2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]])>

In [64]:
tensor2.ndim

3

In [65]:
tf.size(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [70]:
# create a rank 6 tensor
rank6tensor = tf.ones(shape=[2,3,4,5,6,7], dtype = tf.float16)
rank6tensor

<tf.Tensor: shape=(2, 3, 4, 5, 6, 7), dtype=float16, numpy=
array([[[[[[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
          

In [71]:
tf.size(rank6tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=5040>

In [73]:
# pull 1st element from each dims

rank6tensor[:1, :1, :1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1, 1, 1), dtype=float16, numpy=array([[[[[[1.]]]]]], dtype=float16)>

In [74]:
# pull 1st 2 element from each dims

rank6tensor[:2, :2, :2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2, 2, 2), dtype=float16, numpy=
array([[[[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]]],




       [[[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]]]], dtype=float16)>

In [77]:
# get 1st element from each dims from each index except the 2nd lastone
rank6tensor[:1, :1, :1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 1, 1, 6, 1), dtype=float16, numpy=
array([[[[[[1.],
           [1.],
           [1.],
           [1.],
           [1.],
           [1.]]]]]], dtype=float16)>