In [1]:
# fundamental concepts of tensors using tensorflow

import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# creating tensors

scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions
scaler.ndim

0

In [4]:
# creating a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[1,2],
                    [40, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [40,  5]])>

In [7]:
matrix.ndim

2

In [9]:
# Creating tensor

tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[6, 7, 1],
                     [9, 10, 2]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  1],
        [ 9, 10,  2]]])>

In [10]:
tensor.ndim

3

In [16]:
# working with variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor,


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,)

In [17]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [19]:
# let's try to change a element of changeable_tensor
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [20]:
changeable_tensor[1] = 10

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
changeable_tensor[1].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 10])>

In [22]:
unchangeable_tensor[1].assign(10)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [23]:
# Creating random tensor

random_a = tf.random.set_seed(7)
random_a = tf.random.normal(shape=[2,2])
random_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5983449 , 0.06276207],
       [0.14631742, 0.48481876]], dtype=float32)>

In [24]:
# Creating random tensor

random_b = tf.random.set_seed(7)
random_b = tf.random.normal(shape=[2,2])
random_b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5983449 , 0.06276207],
       [0.14631742, 0.48481876]], dtype=float32)>

In [26]:
# Creating random tensor

random_c = tf.random.set_seed(1)
random_c = tf.random.normal(shape=[2,2])
random_c
# random equality depends on set_seed

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1012203 ,  1.5457517 ],
       [ 0.383644  , -0.87965786]], dtype=float32)>

In [28]:
# shuffle a tensor

not_shuffled = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [29]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])>

In [30]:
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])>

In [31]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [35]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled
#every time it changes it's pattern

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])>

In [50]:
# to fixed pattern
tf.random.set_seed(7) # global level seed
shuffled = tf.random.shuffle(not_shuffled, seed = 7) # operation level seed
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])>

In [51]:
# Create a tensor of all 1
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [52]:
tf.zeros(shape=[5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [53]:
import numpy as np
numpy_array = np.arange(5, 29)

In [54]:
numpy_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28])

In [56]:
numpy_array.shape

(24,)

In [57]:
# numpy array to tensor
tensor = tf.constant(numpy_array)

In [58]:
tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28])>

In [59]:
tensor = tf.constant(numpy_array, shape = (3, 8))

In [60]:
tensor

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28]])>

In [61]:
tensor.ndim

2

In [62]:
tensor2 = tf.constant(numpy_array, shape=(2, 3, 4))

In [63]:
tensor2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]])>

In [64]:
tensor2.ndim

3

In [65]:
tf.size(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [70]:
# create a rank 6 tensor
rank6tensor = tf.ones(shape=[2,3,4,5,6,7], dtype = tf.float16)
rank6tensor

<tf.Tensor: shape=(2, 3, 4, 5, 6, 7), dtype=float16, numpy=
array([[[[[[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.]],

          [[1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
           [1., 1., 1., ..., 1., 1., 1.],
          

In [71]:
tf.size(rank6tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=5040>

In [73]:
# pull 1st element from each dims

rank6tensor[:1, :1, :1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1, 1, 1), dtype=float16, numpy=array([[[[[[1.]]]]]], dtype=float16)>

In [74]:
# pull 1st 2 element from each dims

rank6tensor[:2, :2, :2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2, 2, 2), dtype=float16, numpy=
array([[[[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]]],




       [[[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.]]]]]], dtype=float16)>

In [77]:
# get 1st element from each dims from each index except the 2nd lastone
rank6tensor[:1, :1, :1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 1, 1, 6, 1), dtype=float16, numpy=
array([[[[[[1.],
           [1.],
           [1.],
           [1.],
           [1.],
           [1.]]]]]], dtype=float16)>

In [78]:
# mathmetic operations with tensors

tensor

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28]])>

In [79]:
tensor = tf.constant([[1,2], [3,4]])

In [80]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [81]:
tensor +10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [82]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]])>

In [83]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [84]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [87]:
# we can use build-in methods for those operations from tensorflow
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [88]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [91]:
# matrix multiplication

tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]])>

In [92]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [94]:
tensor @ tensor # @ represents tensorflow matmul method

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]])>

In [95]:
X = tf.constant([[1,2,3], [4,5,6]])

In [96]:
X

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [97]:
y = tf.constant([[11, 12], [13, 14], [15, 16]])

In [98]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [15, 16]])>

In [99]:
tf.matmul(X, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 82,  88],
       [199, 214]])>

In [100]:
tf.matmul(y, X)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 59,  82, 105],
       [ 69,  96, 123],
       [ 79, 110, 141]])>

In [101]:
y_ = tf.constant([[11, 22], [33, 44], [55, 66], [77, 88]])

In [102]:
y_


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])>

In [103]:
tf.matmul(X, y_)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [4,2] [Op:MatMul]

In [104]:
tf.matmul(y_, X)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 99, 132, 165],
       [209, 286, 363],
       [319, 440, 561],
       [429, 594, 759]])>

In [105]:
# to avoid shape error we can make matrix traspose or change the shape 

In [106]:
X = tf.constant([[1,2],[3,4],[5,6]])

In [107]:
Y = tf.constant([[7,8],[9,10],[11,12]])

In [108]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [109]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [110]:
tf.tensordot(X, Y, axes = 1)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [113]:
tf.tensordot(X, tf.transpose(Y), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [114]:
tf.tensordot(X, tf.transpose(Y), axes = 0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  9, 11],
         [ 8, 10, 12]],

        [[14, 18, 22],
         [16, 20, 24]]],


       [[[21, 27, 33],
         [24, 30, 36]],

        [[28, 36, 44],
         [32, 40, 48]]],


       [[[35, 45, 55],
         [40, 50, 60]],

        [[42, 54, 66],
         [48, 60, 72]]]])>

In [120]:
# reshape vs transpose

print('Normal Y:', Y)
print('Transposed Y:', tf.transpose(Y))
print('Reshaped Y:', tf.reshape(Y, shape=(2, 3))) # read as human lol

Normal Y: tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Transposed Y: tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
Reshaped Y: tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [122]:
# changing Datatype

X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [123]:
# int32 t0 int16
tf.cast(X, dtype = tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

In [124]:
#int32 to float32
tf.cast(X, dtype = tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [129]:
# float to int
t = tf.constant([1.3, 3.6])

In [130]:
t

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.3, 3.6], dtype=float32)>

In [131]:
tf.cast(t, dtype=tf.int32) # always put the floor value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

In [132]:
t = tf.constant([-3,-4]) # absulate

In [133]:
t

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -4])>

In [134]:
tf.abs(t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [135]:
# Aggregetions
# min
tf.reduce_min(t)

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

In [136]:
#max
tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=int32, numpy=-3>

In [137]:
# mean
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=int32, numpy=-3>

In [138]:
tf.reduce_sum(t) #sum

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [140]:
# varience
tf.reduce_variance(t)

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [145]:
#import tensorflow_probability as tfp

import tensorflow_probability as tfp

In [146]:
tfp.reduce_variance(t)

AttributeError: module 'tensorflow_probability' has no attribute 'reduce_variance'

In [148]:
tfp.stats.variance(t)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [150]:
# Find positional maximum minimum
tf.random.set_seed(7)
t = tf.random.uniform(shape=[50])

In [151]:
t

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.8344538 , 0.23336661, 0.8796519 , 0.04664922, 0.80349684,
       0.9420098 , 0.48560476, 0.9596517 , 0.65881574, 0.11269152,
       0.42992353, 0.60388005, 0.09393823, 0.08232665, 0.87509394,
       0.9595978 , 0.24487329, 0.4698069 , 0.7515631 , 0.83605003,
       0.8556993 , 0.30181408, 0.82694066, 0.49390066, 0.63653564,
       0.29243422, 0.9494889 , 0.5301058 , 0.1835326 , 0.58373356,
       0.89675355, 0.5347773 , 0.29837036, 0.07734811, 0.17663229,
       0.3444836 , 0.4229324 , 0.68379617, 0.4887246 , 0.5376346 ,
       0.91624343, 0.33474946, 0.06718647, 0.84025824, 0.6102561 ,
       0.1546061 , 0.23240829, 0.7687037 , 0.5492232 , 0.54143226],
      dtype=float32)>

In [152]:
tf.argmax(t)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [153]:
tf.argmin(t) # returns index

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [154]:
t[tf.argmax(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9596517>

In [155]:
t[tf.argmin(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.046649218>

In [160]:
# Squeezing a tensor -> removing all single dimns
tf.random.set_seed(7)
t = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 50))

In [161]:
t

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.8344538 , 0.23336661, 0.8796519 , 0.04664922, 0.80349684,
          0.9420098 , 0.48560476, 0.9596517 , 0.65881574, 0.11269152,
          0.42992353, 0.60388005, 0.09393823, 0.08232665, 0.87509394,
          0.9595978 , 0.24487329, 0.4698069 , 0.7515631 , 0.83605003,
          0.8556993 , 0.30181408, 0.82694066, 0.49390066, 0.63653564,
          0.29243422, 0.9494889 , 0.5301058 , 0.1835326 , 0.58373356,
          0.89675355, 0.5347773 , 0.29837036, 0.07734811, 0.17663229,
          0.3444836 , 0.4229324 , 0.68379617, 0.4887246 , 0.5376346 ,
          0.91624343, 0.33474946, 0.06718647, 0.84025824, 0.6102561 ,
          0.1546061 , 0.23240829, 0.7687037 , 0.5492232 , 0.54143226]]]],
      dtype=float32)>

In [162]:
tf.squeeze(t)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.8344538 , 0.23336661, 0.8796519 , 0.04664922, 0.80349684,
       0.9420098 , 0.48560476, 0.9596517 , 0.65881574, 0.11269152,
       0.42992353, 0.60388005, 0.09393823, 0.08232665, 0.87509394,
       0.9595978 , 0.24487329, 0.4698069 , 0.7515631 , 0.83605003,
       0.8556993 , 0.30181408, 0.82694066, 0.49390066, 0.63653564,
       0.29243422, 0.9494889 , 0.5301058 , 0.1835326 , 0.58373356,
       0.89675355, 0.5347773 , 0.29837036, 0.07734811, 0.17663229,
       0.3444836 , 0.4229324 , 0.68379617, 0.4887246 , 0.5376346 ,
       0.91624343, 0.33474946, 0.06718647, 0.84025824, 0.6102561 ,
       0.1546061 , 0.23240829, 0.7687037 , 0.5492232 , 0.54143226],
      dtype=float32)>

In [164]:
tf.squeeze(t).shape

TensorShape([50])

#### One Hot Encoding

indices = [0,1,2,3,5]
indices

In [177]:
indices = [0,1,2,3,5]
tf.one_hot(indices, depth = 6)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [179]:
tf.one_hot(indices, depth=6, on_value='*', off_value='_')

<tf.Tensor: shape=(5, 6), dtype=string, numpy=
array([[b'*', b'_', b'_', b'_', b'_', b'_'],
       [b'_', b'*', b'_', b'_', b'_', b'_'],
       [b'_', b'_', b'*', b'_', b'_', b'_'],
       [b'_', b'_', b'_', b'*', b'_', b'_'],
       [b'_', b'_', b'_', b'_', b'_', b'*']], dtype=object)>

In [185]:
#### Should practices other mathmatics operations

In [186]:
####TF to Numpy Vice-Verca

numpy_j = tf.constant(np.array([1.2, 3.2]))

In [187]:
numpy_j.dtype

tf.float64

In [188]:
pure_tf = tf.constant([1.2, 3.2])

In [189]:
pure_tf.dtype

tf.float32

In [190]:
t2n = np.array(pure_tf)

In [191]:
t2n

array([1.2, 3.2], dtype=float32)

In [192]:
#normal numpy array data type
arr = np.array([1.2, 3.2])

In [193]:
arr.dtype

dtype('float64')

In [194]:
# numpy array float64