1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

---



In [1]:
import tensorflow as tf

In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([7, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [8]:
# Create a matrix more than one dims
matrix = tf.constant([[1,2],
                     [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
matrix.ndim

2

Tensor is an N-dims array. where n can be any number.

2. Find the shape, rank and size of the tensors you created in 1.

---




In [11]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [17]:
scalar.shape, tf.size(scalar), scalar.ndim

(TensorShape([]), <tf.Tensor: shape=(), dtype=int32, numpy=1>, 0)

In [14]:
scalar.ndim

0

In [15]:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [18]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [24]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

---



In [30]:
#the default range is [0, 1) for tf.random.uniform
tensor_one = tf.random.uniform(shape=[5, 300])
tensor_one
print('-------------')
print('-------------')
tensor_two = tf.random.uniform(shape=(5, 300))
tensor_two


-------------
-------------


<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.3548112 , 0.45437527, 0.05482674, ..., 0.11515355, 0.2825606 ,
        0.16674268],
       [0.81571233, 0.9966122 , 0.12788916, ..., 0.82730556, 0.09335887,
        0.12008715],
       [0.8676119 , 0.8121841 , 0.0784353 , ..., 0.16347027, 0.41583323,
        0.3992902 ],
       [0.98271   , 0.10216165, 0.5804908 , ..., 0.51945376, 0.06160271,
        0.15198445],
       [0.7075077 , 0.7095536 , 0.26931548, ..., 0.6879729 , 0.9080746 ,
        0.03882849]], dtype=float32)>

4. Multiply the two tensors you created in 3 using matrix multiplication.


---




In [31]:
multiplication = tf.matmul(tensor_one, tensor_two)
multiplication

InvalidArgumentError: ignored

In [33]:
tensor_one.shape

TensorShape([5, 300])

In [34]:
transpose_tensor_two = tf.transpose(tensor_two)
transpose_tensor_two.shape

TensorShape([300, 5])

In [32]:
multiplication = tf.matmul(tensor_one, tf.transpose(tensor_two))
multiplication

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[71.618835, 73.12355 , 70.14987 , 70.49443 , 75.66005 ],
       [71.797325, 74.126816, 72.103355, 73.92647 , 78.74638 ],
       [72.61735 , 72.76413 , 74.38701 , 72.89404 , 76.24926 ],
       [77.01221 , 79.28808 , 77.773575, 75.84927 , 80.95017 ],
       [70.57883 , 74.000275, 70.98927 , 72.25386 , 74.21423 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

---



In [35]:
dot_product = tf.tensordot(tensor_one, tensor_two)
dot_product

TypeError: ignored

In [37]:
dot_product = tf.tensordot(tensor_one, tensor_two, axes=1)
dot_product

InvalidArgumentError: ignored

In [39]:
dot_product = tf.tensordot(tensor_one, tf.transpose(tensor_two), axes=1)
dot_product

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[71.618835, 73.12355 , 70.14987 , 70.49443 , 75.66005 ],
       [71.797325, 74.126816, 72.103355, 73.92647 , 78.74638 ],
       [72.61735 , 72.76413 , 74.38701 , 72.89404 , 76.24926 ],
       [77.01221 , 79.28808 , 77.773575, 75.84927 , 80.95017 ],
       [70.57883 , 74.000275, 70.98927 , 72.25386 , 74.21423 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
---


In [42]:
another_tensor = tf.random.uniform(shape=(224, 224, 3))
another_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8306067 , 0.4031241 , 0.49396968],
        [0.02809119, 0.94939363, 0.00810158],
        [0.14676058, 0.45752442, 0.35288894],
        ...,
        [0.7965239 , 0.61090004, 0.8022196 ],
        [0.34275317, 0.21994686, 0.12904775],
        [0.25351846, 0.39947724, 0.08828866]],

       [[0.6000353 , 0.5063399 , 0.44458604],
        [0.8953221 , 0.6501788 , 0.89394164],
        [0.29298902, 0.32754636, 0.11526477],
        ...,
        [0.16283333, 0.18930185, 0.7467902 ],
        [0.9120487 , 0.21166587, 0.27991438],
        [0.77477   , 0.59461486, 0.8975587 ]],

       [[0.48994076, 0.09964681, 0.70525515],
        [0.23445499, 0.93510556, 0.509079  ],
        [0.47972202, 0.82836485, 0.0217402 ],
        ...,
        [0.9851464 , 0.03132343, 0.11069882],
        [0.6611512 , 0.3627442 , 0.91665304],
        [0.9062052 , 0.818004  , 0.9803989 ]],

       ...,

       [[0.26372373, 0.8795148 , 0.5678731 ],
        [0.97

7. Find the min and max values of the tensor you created in 6.
---

In [43]:
min = tf.reduce_min(another_tensor)
min

<tf.Tensor: shape=(), dtype=float32, numpy=7.1525574e-06>

In [44]:
max = tf.reduce_max(another_tensor)
max

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999523>

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
---


In [50]:
random = tf.random.Generator.from_seed(42)
tensor_4_rank = random.normal(shape=(1, 224, 224, 3))
tensor_4_rank

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646, -0.7535805 ],
         ...,
         [ 0.07099114, -0.5095768 ,  0.3482001 ],
         [ 0.15985982, -1.9042184 ,  0.9690504 ],
         [ 0.16251186, -0.07330752, -0.360591  ]],

        [[ 0.18739441, -0.73353654,  1.2104433 ],
         [ 1.5603006 , -0.48115277,  0.6335167 ],
         [-0.5612103 ,  0.06994031,  1.6807095 ],
         ...,
         [-1.9460293 , -0.7977275 ,  0.03092833],
         [ 0.8297488 ,  0.12179119,  1.0506107 ],
         [-1.3097638 ,  0.92536974, -1.1787732 ]],

        [[-0.21711822, -0.73974085, -1.3077081 ],
         [-0.7502274 , -0.37715855, -0.30130875],
         [ 1.0943383 ,  0.255803  ,  0.8011465 ],
         ...,
         [-0.32833767, -0.7794747 ,  0.20049338],
         [-0.09002841,  0.07243238, -0.81940895],
         [ 0.3171264 , -1.6143695 , -1.6824651

In [51]:
# squeeze the shape
squeezed_tensor = tf.squeeze(tensor_4_rank)
squeezed_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        ...,
        [ 0.07099114, -0.5095768 ,  0.3482001 ],
        [ 0.15985982, -1.9042184 ,  0.9690504 ],
        [ 0.16251186, -0.07330752, -0.360591  ]],

       [[ 0.18739441, -0.73353654,  1.2104433 ],
        [ 1.5603006 , -0.48115277,  0.6335167 ],
        [-0.5612103 ,  0.06994031,  1.6807095 ],
        ...,
        [-1.9460293 , -0.7977275 ,  0.03092833],
        [ 0.8297488 ,  0.12179119,  1.0506107 ],
        [-1.3097638 ,  0.92536974, -1.1787732 ]],

       [[-0.21711822, -0.73974085, -1.3077081 ],
        [-0.7502274 , -0.37715855, -0.30130875],
        [ 1.0943383 ,  0.255803  ,  0.8011465 ],
        ...,
        [-0.32833767, -0.7794747 ,  0.20049338],
        [-0.09002841,  0.07243238, -0.81940895],
        [ 0.3171264 , -1.6143695 , -1.6824651 ]],

       ...,

     

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
---

In [56]:
a_tensor = tf.constant([1,2,6,4,3,21,55,44,33,22])

In [57]:
a_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  6,  4,  3, 21, 55, 44, 33, 22], dtype=int32)>

In [58]:
a_tensor.ndim

1

In [59]:
max_index = tf.math.argmax(a_tensor)
max_index

<tf.Tensor: shape=(), dtype=int64, numpy=6>

10. One-hot encode the tensor you created in 9.
---

In [64]:
one_hot = tf.one_hot(a_tensor, 56)
one_hot

<tf.Tensor: shape=(10, 56), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.,